// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(63,31,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,638,2^(56.674493))
// 
// Ring
// degree d = 64
// modulus q = 1267650600228229401496703207533, log(q) ~ 100.0
// factors q = q1
// 
// Compression
// D = 33
// gamma = 3595396064892, log(gamma) ~ 41.709288
// 
// Dimensions of secrets
// s1: m1 = 544
// m: l = 0
// s2: m2 = 94
// 
// Size of secrets
// l2(s1) <= alpha = 1.3986823e+8
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [128, 128, 288], bounds: [1.3421773e+8, 39353811.0, 17432.507])
// approximate infinity: yes (psi: 2694.3347, dimension: 288, bound: 6.8507113e+11)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 213030377881.6, log(stdev1/1.55) = 37.0
// stdev2 = 12697.6, log(stdev2/1.55) = 13.0
// stdev3 = 13314398617.6, log(stdev3/1.55) = 33.0
// stdev4 = 54535776737689.6, log(stdev4/1.55) = 45.0
// 
// Repetition rate
// M1 = 3.4330203
// M2 = 1.441481
// M3 = 1.0187689
// M4 = 1.026946
// total = 5.1773629
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.0043579
// MLWE dimension: 63
// MLWE root hermite factor: 1.0043396
// 
// Proof size
// ~ 208.210937500000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241, 1125899906824961]
// bit length of products: [49, 99, 149, 199, 249]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893, -134010426262513]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {2157UL, 68719476736UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {2156UL, 68719476736UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {352576065987964421UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {176288032993982210UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {3595396064892UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {1797698032446UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {8589934592UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {4294967296UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {17062929904530838934UL, 399345124UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {3269560148787580024UL, 7987814365874244514UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {16309642464897295238UL, 8143887741173538224UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {10551679904584050106UL, 346225269359241872UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {14166540343127569559UL, 497066578342450586UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {2951479051793528259UL, 2460UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {11252513884962826486UL, 9UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {14019525496019259228UL, 161229045UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {1078UL, 34359738368UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {539UL, 17179869184UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 2, 1}};
static const unsigned int _param_n[3] = {128, 128, 288};
static const limb_t _param_Bz3sqr_limbs[] = {15612143592367047076UL, 6616UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {872572427803033UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_Pmodq_limbs[] = {4010582755874977692UL, 20193692864UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 2, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {18014398509481984UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {1548722404901665UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 2, 0}};
static const limb_t _param_l2Bsq2_limbs[] = {303892305UL, 0UL};
static const int_t _param_l2Bsq2 = {{(limb_t *)_param_l2Bsq2_limbs, 2, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {10282342038469517860UL, 163470460UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {6536641130270168868UL, 138352800UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _param_Ppmodq_2_limbs[] = {4808452782233849124UL, 89085231UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 2, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {17779787504611178532UL, 30744914UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 2, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {4521220919518664228UL, 28623043UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 2, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1, _param_l2Bsq2};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4};
static const polyring_t _param_ring = {{_param_q, 64, 101, 6, moduli_d64, 5, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 33, 1, 59 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 547, 94, 0, 11, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 547, 94, 9, 2, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 547, 94, 10, 1, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 288, 3, 547, 2, 33, _param_scM3, _param_stdev3sq, 2, 45, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 213208UL }};

static const unsigned int param_Es0[128] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127};
static const unsigned int param_Es1[128] = {128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255};
static const unsigned int param_Es2[288] = {256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543};
static const unsigned int *param_Es[3] = { param_Es0, param_Es1, param_Es2, };
static const unsigned int param_Es_nrows[3] = {128, 128, 288};

static const limb_t param_p_limbs[] = {199034774335489UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {18247655043550023603UL, 34281411415UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 0}};
static const unsigned int param_s1_indices[17] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const lin_params_t param = {{ _param, 2048, param_p, param_pinv, 32, param_s1_indices, 17, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

