// auto-generated by lnp-tbox.sage.
// 
// protocol is statistically complete with correctness error >= 1 - 2^(-3)
// protocol is simulatable under MLWE(61,31,[-1,1])
// protocol is knowledge-sound with knowledge error <= 2^(-127.0) under MSIS(20,348,2^(55.958028))
// 
// Ring
// degree d = 64
// modulus q = 316912650057057350374175804453, log(q) ~ 98.0
// factors q = q1
// 
// Compression
// D = 32
// gamma = 2141080790462, log(gamma) ~ 40.961476
// 
// Dimensions of secrets
// s1: m1 = 256
// m: l = 0
// s2: m2 = 92
// 
// Size of secrets
// l2(s1) <= alpha = 1.3964252e+8
// m unbounded
// s2 uniform in [-nu,nu] = [-1,1]
// 
// Norm proofs
// binary: no
// exact euclidean: yes (dimensions: [128, 128], bounds: [1.3421773e+8, 38543921.0])
// approximate infinity: yes (psi: 2922.8826, dimension: 32, bound: 3.157518e+11)
// 
// Challenge space
// c uniform in [-omega,omega] = [-8,8], o(c)=c, sqrt(l1(o(c)*c)) <= eta = 140
// 
// Standard deviations
// stdev1 = 213030377881.6, log(stdev1/1.55) = 37.0
// stdev2 = 12697.6, log(stdev2/1.55) = 13.0
// stdev3 = 13314398617.6, log(stdev3/1.55) = 33.0
// stdev4 = 27267888368844.8, log(stdev4/1.55) = 44.0
// 
// Repetition rate
// M1 = 3.4261705
// M2 = 1.4303095
// M3 = 1.0187078
// M4 = 1.0228509
// total = 5.1062371
// 
// Security
// MSIS dimension: 20
// MSIS root hermite factor: 1.004335
// MLWE dimension: 61
// MLWE root hermite factor: 1.0043905
// 
// Proof size
// ~ 115.000000000000 KiB
// 
// 50 bit moduli for degree 64: [1125899906840833, 1125899906839937, 1125899906837633, 1125899906826241, 1125899906824961]
// bit length of products: [49, 99, 149, 199, 249]
// inverses: [1, -162099428551732, 296975494591860, 32272507837893, -134010426262513]

#include "lazer.h"
static const limb_t _param_q_limbs[] = {3109UL, 17179869184UL};
static const int_t _param_q = {{(limb_t *)_param_q_limbs, 2, 0}};
static const limb_t _param_qminus1_limbs[] = {3108UL, 17179869184UL};
static const int_t _param_qminus1 = {{(limb_t *)_param_qminus1_limbs, 2, 0}};
static const limb_t _param_m_limbs[] = {148015269423193646UL, 0UL};
static const int_t _param_m = {{(limb_t *)_param_m_limbs, 2, 0}};
static const limb_t _param_mby2_limbs[] = {74007634711596823UL, 0UL};
static const int_t _param_mby2 = {{(limb_t *)_param_mby2_limbs, 2, 0}};
static const limb_t _param_gamma_limbs[] = {2141080790462UL, 0UL};
static const int_t _param_gamma = {{(limb_t *)_param_gamma_limbs, 2, 0}};
static const limb_t _param_gammaby2_limbs[] = {1070540395231UL, 0UL};
static const int_t _param_gammaby2 = {{(limb_t *)_param_gammaby2_limbs, 2, 0}};
static const limb_t _param_pow2D_limbs[] = {4294967296UL, 0UL};
static const int_t _param_pow2D = {{(limb_t *)_param_pow2D_limbs, 2, 0}};
static const limb_t _param_pow2Dby2_limbs[] = {2147483648UL, 0UL};
static const int_t _param_pow2Dby2 = {{(limb_t *)_param_pow2Dby2_limbs, 2, 0}};
static const limb_t _param_Bsq_limbs[] = {7888158922245664569UL, 130462094UL, 0UL, 0UL};
static const int_t _param_Bsq = {{(limb_t *)_param_Bsq_limbs, 4, 0}};
static const limb_t _param_scM1_limbs[] = {10859156029414079454UL, 7861457528717932160UL, 3UL};
static const int_t _param_scM1 = {{(limb_t *)_param_scM1_limbs, 3, 0}};
static const limb_t _param_scM2_limbs[] = {15570436064649696338UL, 7937809064446605904UL, 1UL};
static const int_t _param_scM2 = {{(limb_t *)_param_scM2_limbs, 3, 0}};
static const limb_t _param_scM3_limbs[] = {15273063275304242824UL, 345098352277887717UL, 1UL};
static const int_t _param_scM3 = {{(limb_t *)_param_scM3_limbs, 3, 0}};
static const limb_t _param_scM4_limbs[] = {11197539752857389546UL, 421525344714025793UL, 1UL};
static const int_t _param_scM4 = {{(limb_t *)_param_scM4_limbs, 3, 0}};
static const limb_t _param_stdev1sq_limbs[] = {2951479051793528259UL, 2460UL, 0UL, 0UL};
static const int_t _param_stdev1sq = {{(limb_t *)_param_stdev1sq_limbs, 4, 0}};
static const limb_t _param_stdev2sq_limbs[] = {161229046UL, 0UL, 0UL, 0UL};
static const int_t _param_stdev2sq = {{(limb_t *)_param_stdev2sq_limbs, 4, 0}};
static const limb_t _param_stdev3sq_limbs[] = {11252513884962826486UL, 9UL, 0UL, 0UL};
static const int_t _param_stdev3sq = {{(limb_t *)_param_stdev3sq_limbs, 4, 0}};
static const limb_t _param_stdev4sq_limbs[] = {8116567392432202711UL, 40307261UL, 0UL, 0UL};
static const int_t _param_stdev4sq = {{(limb_t *)_param_stdev4sq_limbs, 4, 0}};
static const limb_t _param_inv2_limbs[] = {1554UL, 8589934592UL};
static const int_t _param_inv2 = {{(limb_t *)_param_inv2_limbs, 2, 1}};
static const limb_t _param_inv4_limbs[] = {777UL, 4294967296UL};
static const int_t _param_inv4 = {{(limb_t *)_param_inv4_limbs, 2, 1}};
static const unsigned int _param_n[2] = {128, 128};
static const limb_t _param_Bz3sqr_limbs[] = {15612143592367047076UL, 6616UL, 0UL, 0UL};
static const int_t _param_Bz3sqr = {{(limb_t *)_param_Bz3sqr_limbs, 4, 0}};
static const limb_t _param_Bz4_limbs[] = {436286213901516UL, 0UL};
static const int_t _param_Bz4 = {{(limb_t *)_param_Bz4_limbs, 2, 0}};
static const limb_t _param_Pmodq_limbs[] = {13879464849622830194UL, 3414658269UL};
static const int_t _param_Pmodq = {{(limb_t *)_param_Pmodq_limbs, 2, 1}};
static const limb_t _param_l2Bsq0_limbs[] = {18014398509481984UL, 0UL};
static const int_t _param_l2Bsq0 = {{(limb_t *)_param_l2Bsq0_limbs, 2, 0}};
static const limb_t _param_l2Bsq1_limbs[] = {1485633833817313UL, 0UL};
static const int_t _param_l2Bsq1 = {{(limb_t *)_param_l2Bsq1_limbs, 2, 0}};
static const limb_t _param_Ppmodq_0_limbs[] = {13628522360753847527UL, 163444283UL};
static const int_t _param_Ppmodq_0 = {{(limb_t *)_param_Ppmodq_0_limbs, 2, 1}};
static const limb_t _param_Ppmodq_1_limbs[] = {12332779290313902951UL, 138327185UL};
static const int_t _param_Ppmodq_1 = {{(limb_t *)_param_Ppmodq_1_limbs, 2, 1}};
static const limb_t _param_Ppmodq_2_limbs[] = {1092987680550018663UL, 89061062UL};
static const int_t _param_Ppmodq_2 = {{(limb_t *)_param_Ppmodq_2_limbs, 2, 1}};
static const limb_t _param_Ppmodq_3_limbs[] = {16226047631390220263UL, 30727892UL};
static const int_t _param_Ppmodq_3 = {{(limb_t *)_param_Ppmodq_3_limbs, 2, 1}};
static const limb_t _param_Ppmodq_4_limbs[] = {3832172050168071911UL, 28606824UL};
static const int_t _param_Ppmodq_4 = {{(limb_t *)_param_Ppmodq_4_limbs, 2, 1}};
static const int_srcptr _param_l2Bsq[] = {_param_l2Bsq0, _param_l2Bsq1};
static const int_srcptr _param_Ppmodq[] = {_param_Ppmodq_0, _param_Ppmodq_1, _param_Ppmodq_2, _param_Ppmodq_3, _param_Ppmodq_4};
static const polyring_t _param_ring = {{_param_q, 64, 99, 6, moduli_d64, 5, _param_Pmodq, _param_Ppmodq, _param_inv2}};
static const dcompress_params_t _param_dcomp = {{ _param_q, _param_qminus1, _param_m, _param_mby2, _param_gamma, _param_gammaby2, _param_pow2D, _param_pow2Dby2, 32, 0, 58 }};
static const abdlop_params_t _param_tbox = {{ _param_ring, _param_dcomp, 258, 92, 0, 11, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_eval_ = {{ _param_ring, _param_dcomp, 258, 92, 9, 2, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const abdlop_params_t _param_quad_many_ = {{ _param_ring, _param_dcomp, 258, 92, 10, 1, 20, _param_Bsq, 1, 8, 5, 140, 1, 37, _param_scM1, _param_stdev1sq, 2, 13, _param_scM2, _param_stdev2sq}};
static const lnp_quad_eval_params_t _param_quad_eval = {{ _param_quad_eval_, _param_quad_many_, 2}};
static const lnp_tbox_params_t _param = {{ _param_tbox, _param_quad_eval, 0, _param_n, 32, 2, 258, 2, 33, _param_scM3, _param_stdev3sq, 2, 44, _param_scM4, _param_stdev4sq, _param_Bz3sqr, _param_Bz4, &_param_l2Bsq[0], _param_inv4, 117760UL }};

static const unsigned int param_Es0[128] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127};
static const unsigned int param_Es1[128] = {128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255};
static const unsigned int *param_Es[2] = { param_Es0, param_Es1, };
static const unsigned int param_Es_nrows[2] = {128, 128};

static const limb_t param_p_limbs[] = {105548820262913UL};
static const int_t param_p = {{(limb_t *)param_p_limbs, 1, 0}};
static const limb_t param_pinv_limbs[] = {13475278031849151176UL, 7841424454UL};
static const int_t param_pinv = {{(limb_t *)param_pinv_limbs, 2, 1}};
static const unsigned int param_s1_indices[8] = {0, 1, 2, 3, 4, 5, 6, 7};
static const lin_params_t param = {{ _param, 2048, param_p, param_pinv, 32, param_s1_indices, 8, NULL, 0,  NULL, 0, param_Es, param_Es_nrows, NULL, NULL }};

